spring:
  application:
    name: MailingService
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:127.0.0.1}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE:postgres}
    username: ${POSTGRESQL_USERNAME:root}
    password: ${POSTGRESQL_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev